name: StaticScanVeraCode

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  veracode-static-scan:
    runs-on: ubuntu-latest
    environment: staticscan
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Zip entire project for Veracode
        run: 7z a LibreChat.zip . '-xr!.git'

      - name: Get timestamp
        run: echo TIMESTAMP=$(date +%Y-%m-%d_%H:%M:%S) >> $GITHUB_ENV

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: LibreChat
          createprofile: false
          filepath: LibreChat.zip
          version: ${{env.TIMESTAMP}}
          vid: ${{ secrets.VERACODE_API_KEY_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY_SECRET }}
          deleteincompletescan: 1

